<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketPeak.Shared.Kernel\TicketPeak.Shared.Kernel.csproj" />
    <ProjectReference Include="..\TicketPeak.Modules.Catalog\TicketPeak.Modules.Catalog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TicketPeak.UnitTests" />
  </ItemGroup>

</Project>
