<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketPeak.Shared.Kernel\TicketPeak.Shared.Kernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TicketPeak.UnitTests" />
  </ItemGroup>

</Project>
